// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBROWgKdbedj8MYo9hBMGGaxRUPRQfkD7A',
    appId: '1:182368786465:web:f9f95c5eceaefa7835ab60',
    messagingSenderId: '182368786465',
    projectId: 'food-delivery-5e9fe',
    authDomain: 'food-delivery-5e9fe.firebaseapp.com',
    storageBucket: 'food-delivery-5e9fe.appspot.com',
    measurementId: 'G-4940VS7BF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsD5ev5o0uBjFtrfGfrfzJfPykphzy9UI',
    appId: '1:182368786465:android:7186318411c9b72c35ab60',
    messagingSenderId: '182368786465',
    projectId: 'food-delivery-5e9fe',
    storageBucket: 'food-delivery-5e9fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCB6BKZ90DfryCG4Ylb9v-KqaMk5YG1Lg',
    appId: '1:182368786465:ios:cafb3c3fccb36ca735ab60',
    messagingSenderId: '182368786465',
    projectId: 'food-delivery-5e9fe',
    storageBucket: 'food-delivery-5e9fe.appspot.com',
    iosClientId: '182368786465-84sa6dk0qo9nccohoet4n709vdjjf1ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.annaBazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCB6BKZ90DfryCG4Ylb9v-KqaMk5YG1Lg',
    appId: '1:182368786465:ios:2bc3f61697efb6ed35ab60',
    messagingSenderId: '182368786465',
    projectId: 'food-delivery-5e9fe',
    storageBucket: 'food-delivery-5e9fe.appspot.com',
    iosClientId: '182368786465-fmpum16sd630fkpeaenol675t2td87or.apps.googleusercontent.com',
    iosBundleId: 'com.example.annaBazar.RunnerTests',
  );
}
